export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as Sidebar } from "./Header/Sidebar";
export { default as BackdropLoader } from "./Loaders/BackdropLoader";
export { default as Slider } from "./Slider/Slider";
export { default as MyAccordion } from "./MyAccordion/MyAccordion";
export { default as ProductInfo } from "./ProductInfo/ProductInfo";
export { default as Drawer } from "./Drawer/Drawer";
export { default as MyModal } from "./Modal/MyModal";
